### ISSUE TITLE
DrRacket renaming is doing weird things

### ISSUE THREAD

**Issue by AlexKnauth** [soegaard/infix#3]
If I have this program in DrRacket:

``` racket
#lang at-exp racket
(require infix)
(let ([a '(1 1)] [b '(2 3)] [+ (λ (a b) (map + a b))])
  @${a+b})
```

And then I right-click on the a in `@${a+b}` then the check-syntax arrow points the the right thing, but the menu pops up with an option saying `rename +`, then if I proceed to rename it to, say `-`, then it changes it to:

``` racket
(let ([- '(1 1)] [b '(2 3)] [- (λ (a b) (map + a b))])
  @${--b})
```

In other words, it renames both `a` and `+` to `-`.
Do you have any idea what could be causing this?

**Comment by soegaard** [comment]
Note that if you right click at + the menu says rename b.
It means there is an off by 1 error for the pos stored in the source location.

**Comment by AlexKnauth** [comment]
If it was just an off by 1 error, would it rename both `a` and `+`?

**Comment by soegaard** [comment]
Just tried the same thing with:  ($ "a+b")  and it show the same error.
I think this means the error is in the parser.

**Comment by soegaard** [comment]
Oh! It renames both...

That is indeed odd.

2015-04-25 23:21 GMT+02:00 Alex Knauth notifications@github.com:

> If it was just an off by 1 error, would it rename both a and +?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/soegaard/infix/issues/3#issuecomment-96278878.

## 

## 

Jens Axel Søgaard

**Comment by soegaard** [comment]
I looked into this some more. At first I forgot that the column numbers and positions that DrRacket displays in the status line are _not_ the same as the columns and positions in syntax objects, so I thought something was off. 

At some point my theory was that the syntax object representing "a+b" has the position and column of the " (not the first a). However since the arrows are drawn correctly - it is also a possibility that the DrRacket renamer is confused by identifiers embedded in strings. 

I will try to make a minimal stand-alone example without using the infix package to test that theory.

The code for the DrRacket renaming is in:  https://github.com/racket/drracket/blob/7eacf4a845788565bbc34af7efd593eae156dccd/drracket/drracket/private/syncheck/gui.rkt

**Comment by soegaard** [comment]
The following minimal examples shows the same problem:

#lang racket
;;; Minimal example that show a problem when renaming
;;; identifiers that bind an identifers whose name
;;; is a substring.

;;; The example below shows correct arrows (both bound and binding identifiers).
;;; Renaming a, b or + in the binding clauses of the let works.
;;; Renaming (by right clicking) the a in the string renames both a and + !

(define-syntax ($ stx)
  (syntax-case stx ()
    [(_ str)
     (let ()
       (define s (syntax-e #'str))
       (define x  (string->symbol (string (string-ref s 0))))
       (define y  (string->symbol (string (string-ref s 2))))
       (define op (string->symbol (string (string-ref s 1))))
       (define src  (syntax-source stx))
       (define line (syntax-line     #'str))
       (define pos  (syntax-position #'str))
       (define col  (syntax-column   #'str))  ; column of "
       (displayln (list 'col col))
       (define span 1)  
       (define (make-srcloc i) 
         ; add 1 to get past the "
         (list src line (+ col 1 i) (+ pos 1 i) span))
       (with-syntax ([x  (datum->syntax #'str x  (make-srcloc 0) #'str)]
                     [y  (datum->syntax #'str y  (make-srcloc 2) #'str)]
                     [op (datum->syntax #'str op (make-srcloc 1) #'str)])
         #'(op x y)))]))

(let ([a 2]
      [b 3]
      [+ *])
  ($ "a+b"))

**Comment by soegaard** [comment]
Fixed in https://github.com/racket/drracket/commit/660286fe1f3cec80bf0594b22b470586042ef0c3

Thanks for the report!
